### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by IDontHaveIdea** [nhydock/OpenKoikatsuPlugins#2]
Hi,

Tried to test OKS.TopMe but when trying to compile it it ask for credentials which are not specified.  Used my github ones no luck.
Downloaded the package BepInEx.UnityInput and tried to manually install again no luck.  The package does not have a net46 target which is the target for Sunshine.  Ended up compiling with and did an assembly reference.

What I really need is instructions how to install and if I find BepInEx.UnityInput useful in any plugin I make how can the dll be distributed.  I really like this idea and it may solve some issues I have.  Any help appreciated in advance.

**Comment by nhydock** [comment]
net35 code still works in net46.  After compiling OKS.TopMe using the nuget package, you'll still need the UnityInput dll in your bepin plugins for KKS, which is distributed separately as it's a runtime dependency.  

Precompiled releases are available for download from the project repo.
https://github.com/nhydock/BepInEx.UnityInput/releases/tag/1.0.0

**Comment by nhydock** [comment]
wait, crap, it's not there.  Sorry, that's my bad, there's supposed to be binaries available for direct download

**Comment by IDontHaveIdea** [comment]
Thanks.
